version: 2.0
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      - image: consul:1.5.2
        environment:
          - CONSUL_LOCAL_CONFIG={ "bind_addr": "127.0.0.1", "server": true, "bootstrap": true, "acl_datacenter": "dc1", "acl_master_token": "eba37d50-2fd8-42f2-b9f6-9c7c7a55890e", "acl_default_policy": "allow", "encrypt": "d8wu8CSUrqgtjVsvcBPmhQ==" }
        command: agent -dev
        
    steps: 
      - checkout
      - dotnet test 