version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet build
  
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      - image: consul:1.5.2
        environment:
          - 'CONSUL_LOCAL_CONFIG={ "bind_addr": "127.0.0.1", "server": true, "bootstrap": true, "acl_datacenter": "dc1", "acl_master_token": "eba37d50-2fd8-42f2-b9f6-9c7c7a55890e", "acl_default_policy": "allow", "encrypt": "d8wu8CSUrqgtjVsvcBPmhQ==" }'
        command: agent -dev
        
    steps: 
      - checkout
      - run: dotnet test --logger "trx;LogFileName=~/artifacts/junit/results.trx"
      - run:
          name: test results
          command: |
            dotnet tool install -g trx2junit
            export PATH="$PATH:/root/.dotnet/tools"
            trx2junit ~/artifacts/junit/results.trx
      - run:
            name: remove trx
            command: rm -f ~/artifacts/junit/results.trx
      - store_test_results:
          path: ~/artifacts/junit
      - store_artifacts:
          path: ~/artifacts/junit
          destination: TestResults
        
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test